// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infra.Data.Contexts;

#nullable disable

namespace Project.Infra.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20241120100301_Fix")]
    partial class Fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Domain.Entities.Citizens.Citizen", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("HouseholdCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PassportCode")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonalizedCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UniqueCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("Project.Domain.Entities.Offices.Office", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("Project.Domain.Entities.Offices.OfficePlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("WorkEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("OfficePlans");
                });

            modelBuilder.Entity("Project.Domain.Entities.Offices.Shift", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Project.Domain.Entities.Offices.WorkCalendar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Holidays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WorkStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("WorkCalendars");
                });

            modelBuilder.Entity("Project.Domain.Entities.Plans.Plan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Project.Domain.Entities.Province.Province", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5078),
                            IsRemoved = false,
                            Name = "AzarbaijanSharghi"
                        },
                        new
                        {
                            Id = 2L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5104),
                            IsRemoved = false,
                            Name = "AzarbaijanGharbi"
                        },
                        new
                        {
                            Id = 3L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5113),
                            IsRemoved = false,
                            Name = "Ardabil"
                        },
                        new
                        {
                            Id = 4L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5123),
                            IsRemoved = false,
                            Name = "Isfahan"
                        },
                        new
                        {
                            Id = 5L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5134),
                            IsRemoved = false,
                            Name = "Alborz"
                        },
                        new
                        {
                            Id = 6L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5145),
                            IsRemoved = false,
                            Name = "Ilam"
                        },
                        new
                        {
                            Id = 7L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5154),
                            IsRemoved = false,
                            Name = "Bushehr"
                        },
                        new
                        {
                            Id = 8L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5164),
                            IsRemoved = false,
                            Name = "Tehran"
                        },
                        new
                        {
                            Id = 9L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5173),
                            IsRemoved = false,
                            Name = "ChaharmahaloBakhtiari"
                        },
                        new
                        {
                            Id = 10L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5183),
                            IsRemoved = false,
                            Name = "KhorasanJonubi"
                        },
                        new
                        {
                            Id = 11L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5192),
                            IsRemoved = false,
                            Name = "KhorasanRazavi"
                        },
                        new
                        {
                            Id = 12L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5201),
                            IsRemoved = false,
                            Name = "KhorasanShomali"
                        },
                        new
                        {
                            Id = 13L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5211),
                            IsRemoved = false,
                            Name = "Khuzestan"
                        },
                        new
                        {
                            Id = 14L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5220),
                            IsRemoved = false,
                            Name = "Zanjan"
                        },
                        new
                        {
                            Id = 15L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5229),
                            IsRemoved = false,
                            Name = "Semnan"
                        },
                        new
                        {
                            Id = 16L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5237),
                            IsRemoved = false,
                            Name = "SistanoBaluchestan"
                        },
                        new
                        {
                            Id = 17L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5248),
                            IsRemoved = false,
                            Name = "Fars"
                        },
                        new
                        {
                            Id = 18L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5258),
                            IsRemoved = false,
                            Name = "Qazvin"
                        },
                        new
                        {
                            Id = 19L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5266),
                            IsRemoved = false,
                            Name = "Qom"
                        },
                        new
                        {
                            Id = 20L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5275),
                            IsRemoved = false,
                            Name = "Kurdistan"
                        },
                        new
                        {
                            Id = 21L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5322),
                            IsRemoved = false,
                            Name = "Kerman"
                        },
                        new
                        {
                            Id = 22L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5332),
                            IsRemoved = false,
                            Name = "Kermanshah"
                        },
                        new
                        {
                            Id = 23L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5342),
                            IsRemoved = false,
                            Name = "KohgiluyehoBoyerahmad"
                        },
                        new
                        {
                            Id = 24L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5351),
                            IsRemoved = false,
                            Name = "Golestan"
                        },
                        new
                        {
                            Id = 25L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5361),
                            IsRemoved = false,
                            Name = "Gilan"
                        },
                        new
                        {
                            Id = 26L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5370),
                            IsRemoved = false,
                            Name = "Lorestan"
                        },
                        new
                        {
                            Id = 27L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5379),
                            IsRemoved = false,
                            Name = "Mazandaran"
                        },
                        new
                        {
                            Id = 28L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5389),
                            IsRemoved = false,
                            Name = "Markazi"
                        },
                        new
                        {
                            Id = 29L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5398),
                            IsRemoved = false,
                            Name = "Hormozgan"
                        },
                        new
                        {
                            Id = 30L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5407),
                            IsRemoved = false,
                            Name = "Hamadan"
                        },
                        new
                        {
                            Id = 31L,
                            InsertTime = new DateTime(2024, 11, 20, 13, 33, 0, 708, DateTimeKind.Local).AddTicks(5416),
                            IsRemoved = false,
                            Name = "Yazd"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Turns.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Project.Domain.Entities.Users.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsRemoved = false,
                            Name = "Citizen"
                        },
                        new
                        {
                            Id = 2L,
                            IsRemoved = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3L,
                            IsRemoved = false,
                            Name = "Operator"
                        });
                });

            modelBuilder.Entity("Project.Domain.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Domain.Entities.Users.UserInRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("InsertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RemoveTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInRole");
                });

            modelBuilder.Entity("Project.Domain.Entities.Offices.Office", b =>
                {
                    b.HasOne("Project.Domain.Entities.Province.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Project.Domain.Entities.Users.UserInRole", b =>
                {
                    b.HasOne("Project.Domain.Entities.Users.Role", "Role")
                        .WithMany("UserInRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.Users.User", "User")
                        .WithMany("UserInRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Domain.Entities.Users.Role", b =>
                {
                    b.Navigation("UserInRoles");
                });

            modelBuilder.Entity("Project.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("UserInRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
